version: "3"
services:
  nginx:
    container_name: laravel-api-example-nginx
    image: nginx:1.17
    ports:
      - "8000:80"
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker/php
    container_name: laravel-api-example-php-fpm
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  db:
    container_name: laravel-api-example-php-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'laravel-api-example'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "33066:3306"
