version: "3"
services:
  nginx:
    container_name: php-in-docker-nginx
    image: nginx:1.17
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php-in-docker-fpm
    image: php:7.4-fpm
    volumes:
      - ./public:/var/www/html/public
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "3306:33066"
